<a href="https://colab.research.google.com/github/jc020230/practiceai/blob/main/2%EC%9E%A5_5_subsetting_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Subsetting the data

## About the Data
In this notebook, we will be working with earthquake data from September 18, 2018 - October 13, 2018 (obtained from the US Geological Survey (USGS) using the [USGS API](https://earthquake.usgs.gov/fdsnws/event/1/))

## Setup
We will be working with the `data/earthquakes.csv` file again, so we need to handle our imports and read it in.

**한글 요약 (진짜 많이 쓰는 것들)**

- 열 고르기: `df['열']` (하나) / `df[['열1', '열2']]` (여러 개, 대괄호 두 개 사용함)
- 행 자르기: `df[시작:끝]` -> 끝 번호 미포함
- `loc`: 이름(라벨)으로 고르기 `df.loc[행, 열]` -> 끝 포함
- `iloc`: 위치 번호로 고르기 `df.iloc[행, 열]` -> 끝 미포함
- 필터링: `df[df.열 > 값]` -> 조건에 맞는 행만. 조건 여러 개면 `&`(그리고), `|`(또는) 쓰고 각 조건은 괄호로 감싸기

loc / iloc 끝 포함 여부가 다른 게 제일 헷갈리는 부분. l = label(이름), i = integer(번호)로 기억

In [ ]:
import pandas as pd

# 지진 데이터 읽기
df = pd.read_csv('data/earthquakes.csv')

## Selecting columns
Grab an entire column using attribute notation:

In [ ]:
# df.열이름 → 열 하나 꺼내기 (결과는 Series로 나옴)
# 점(.) 찍고 열 이름 쓰는 방식. 편하지만 열 이름에 공백이나 특수문자가 있으면 안 됨
df.mag

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

Grab an entire column using dictionary syntax:

In [ ]:
# df['열이름'] → 똑같이 열 하나 꺼내기. 딕셔너리에서 키로 값 꺼내는 것과 같은 문법
# 이 방식이 더 안전함 (열 이름에 공백 있어도 되고, 변수로 열 이름 넣을 수도 있음)
df['mag']

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

Selecting multiple columns:

In [ ]:
# 열 여러 개 꺼내기 → 대괄호 안에 리스트를 넣음. 그래서 대괄호가 두 겹 [[ ]]
# df[ ['mag', 'title'] ] 이렇게 띄어서 보면 이해 쉬움. 바깥 []는 꺼내기, 안쪽 []는 리스트
# 결과는 데이터프레임 (열이 2개니까)
df[['mag', 'title']]

       mag                                     title
0     1.35             M 1.4 - 9km NE of Aguanga, CA
1     1.29             M 1.3 - 9km NE of Aguanga, CA
2     3.42             M 3.4 - 8km NE of Aguanga, CA
3     0.44             M 0.4 - 9km NE of Aguanga, CA
4     2.16             M 2.2 - 10km NW of Avenal, CA
...    ...                                       ...
9327  0.62      M 0.6 - 9km ENE of Mammoth Lakes, CA
9328  1.00               M 1.0 - 3km W of Julian, CA
9329  2.40  M 2.4 - 35km NNE of Hatillo, Puerto Rico
9330  1.10             M 1.1 - 9km NE of Aguanga, CA
9331  0.66             M 0.7 - 9km NE of Aguanga, CA

[9332 rows x 2 columns]

Selecting columns using list comprehensions and string operations:

In [ ]:
# 열 이름 리스트를 조합해서 꺼내기
# ['title', 'time'] + [mag로 시작하는 열들] → 리스트 + 리스트 = 합친 리스트
# col.startswith('mag') → 열 이름이 'mag'로 시작하나? → mag, magType 두 개
# 아래 3개 셀에서 하나씩 뜯어서 설명해줌
df[
    ['title', 'time']
    + [col for col in df.columns if col.startswith('mag')]
]

                                         title           time   mag magType
0                M 1.4 - 9km NE of Aguanga, CA  1539475168010  1.35      ml
1                M 1.3 - 9km NE of Aguanga, CA  1539475129610  1.29      ml
2                M 3.4 - 8km NE of Aguanga, CA  1539475062610  3.42      ml
3                M 0.4 - 9km NE of Aguanga, CA  1539474978070  0.44      ml
4                M 2.2 - 10km NW of Avenal, CA  1539474716050  2.16      md
...                                        ...            ...   ...     ...
9327      M 0.6 - 9km ENE of Mammoth Lakes, CA  1537230228060  0.62      md
9328               M 1.0 - 3km W of Julian, CA  1537230135130  1.00      ml
9329  M 2.4 - 35km NNE of Hatillo, Puerto Rico  1537229908180  2.40      md
9330             M 1.1 - 9km NE of Aguanga, CA  1537229545350  1.10      ml
9331             M 0.7 - 9km NE of Aguanga, CA  1537228864470  0.66      ml

[9332 rows x 4 columns]

Breaking down this example:
1. the list comprehension

In [ ]:
# 1단계: df.columns(열 이름 26개)를 하나씩 꺼내서(col) 'mag'로 시작하는 것만 남김
# -> ['mag', 'magType']
[col for col in df.columns if col.startswith('mag')]

['mag', 'magType']

2. assembling the list

In [ ]:
# 2단계: 리스트 두 개를 + 로 합침
# \ 는 "줄이 길어서 다음 줄에 이어 쓸게"라는 표시
# -> ['title', 'time', 'mag', 'magType']
['title', 'time'] \
+ [col for col in df.columns if col.startswith('mag')]

['title', 'time', 'mag', 'magType']

3. using this list as the list of columns

In [ ]:
# 3단계: 합친 리스트를 df[ ]에 넣어서 그 열들만 꺼냄
df[
    ['title', 'time']
    + [col for col in df.columns if col.startswith('mag')]
]

                                         title           time   mag magType
0                M 1.4 - 9km NE of Aguanga, CA  1539475168010  1.35      ml
1                M 1.3 - 9km NE of Aguanga, CA  1539475129610  1.29      ml
2                M 3.4 - 8km NE of Aguanga, CA  1539475062610  3.42      ml
3                M 0.4 - 9km NE of Aguanga, CA  1539474978070  0.44      ml
4                M 2.2 - 10km NW of Avenal, CA  1539474716050  2.16      md
...                                        ...            ...   ...     ...
9327      M 0.6 - 9km ENE of Mammoth Lakes, CA  1537230228060  0.62      md
9328               M 1.0 - 3km W of Julian, CA  1537230135130  1.00      ml
9329  M 2.4 - 35km NNE of Hatillo, Puerto Rico  1537229908180  2.40      md
9330             M 1.1 - 9km NE of Aguanga, CA  1537229545350  1.10      ml
9331             M 0.7 - 9km NE of Aguanga, CA  1537228864470  0.66      ml

[9332 rows x 4 columns]

## Slicing
### Selecting rows
Using row numbers (inclusive of first index, exclusive of last):

In [ ]:
# df[숫자:숫자] -> 행 자르기(슬라이싱).
# 100:103 -> 100번부터 103 직전까지 = 100, 101, 102 (3행). 끝 번호는 포함 안 됨
df[100:103]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
100,NaN,NaN,20280310,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20280310,",1.20,ml,...,",ak,",automatic,1539435449480,"M 1.2 - 25km NW of Ester, Alaska",0,earthquake,",geoserve,origin,",-540.0,1539443551010,https://earthquake.usgs.gov/earthquakes/eventp...
101,NaN,NaN,73096756,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01355,NaN,185.0,",nc73096756,",0.59,md,...,",nc,",automatic,1539435391320,"M 0.6 - 8km ESE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539439802162,https://earthquake.usgs.gov/earthquakes/eventp...
102,NaN,NaN,37388730,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.02987,NaN,39.0,",ci37388730,",1.33,ml,...,",ci,",automatic,1539435293090,"M 1.3 - 8km ENE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1539435940470,https://earthquake.usgs.gov/earthquakes/eventp...

### Selecting rows and columns with chaining

In [ ]:
# 열 먼저 고르고(['title', 'time']) → 그 결과에서 행 자르기([100:103])
# 이렇게 연달아 쓰는 걸 chaining(체이닝, 연결)이라고 함. 왼쪽부터 순서대로 읽으면 됨
df[['title', 'time']][100:103]

                                    title           time
100      M 1.2 - 25km NW of Ester, Alaska  1539435449480
101  M 0.6 - 8km ESE of Mammoth Lakes, CA  1539435391320
102        M 1.3 - 8km ENE of Aguanga, CA  1539435293090

Order doesn't matter here:

In [ ]:
# 행 먼저 자르고 열 고르기 vs 열 먼저 고르고 행 자르기
# .equals() → 두 데이터프레임이 완전히 같나? → True. 순서 상관없음
df[100:103][['title', 'time']].equals(
    df[['title', 'time']][100:103]
)

True

So we know how to select rows and columns, but can we update values? Well, if we try using what we have learned so far, we will see the following warning:

In [ ]:
# 110~112행의 title을 소문자로 바꿔서 다시 넣기 시도
# .str.lower() → 문자열 열을 전부 소문자로 (.str 을 붙이면 문자열 기능들을 쓸 수 있음)
# 뜻: "너 지금 원본이 아니라 복사본에 값을 넣으려는 것 같은데? .loc를 써라"
# df[110:113]['title'] 처럼 두 번 꺼낸 것에 값을 넣으면 원본에 반영될지 안 될지 애매해서 경고하는 거임
# -> 값을 바꿀 때는 아래 나오는 .loc를 쓰는 게 맞다고 보면 됨
df[110:113]['title'] = df[110:113]['title'].str.lower()

/home/stefaniemolin/book_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

Note that it worked here, but `pandas` says we were setting a value on a copy of a slice and that we should use `loc` instead (topic of the following section):

In [ ]:
# 확인해보니 이번엔 바뀌긴 했음 (소문자로 나옴). 근데 항상 되는 게 아니라서 경고를 낸 거임(구글 코랩에서는 됨)
df[110:113]['title']

110               m 1.1 - 35km s of ester, alaska
111    m 1.9 - 93km wnw of arctic village, alaska
112      m 0.9 - 20km wsw of smith valley, nevada
Name: title, dtype: object

## Indexing

Now if we do this with `loc` as the warning suggests, everything goes smoothly. Note we have to lower the end index by one since `loc` is inclusive of endpoints:

In [ ]:
# .loc[행, 열] → 행과 열을 '이름(라벨)'으로 골라내는 방식. 값 바꿀 때 이걸 써야 함
# .loc는 끝 번호를 포함함. 그래서 110:113이 아니라 110:112로 써야 110,111,112 세 행
# (df[100:103]은 끝 미포함 / df.loc[100:102]는 끝 포함.)
df.loc[110:112, 'title'] = df.loc[110:112, 'title'].str.lower()
# 경고 없이 잘 바뀜
df.loc[110:112, 'title']

110               m 1.1 - 35km s of ester, alaska
111    m 1.9 - 93km wnw of arctic village, alaska
112      m 0.9 - 20km wsw of smith valley, nevada
Name: title, dtype: object

### Indexing with `loc`
Selection of the format `loc[row_indexer, column_indexer]` where `:` can be used to select all:

In [ ]:
# .loc[:, 'title'] -> 모든 행(:)의 title 열
# : 하나만 쓰면 "전부"라는 뜻. df['title']과 결과 같음
df.loc[:,'title']

0                  M 1.4 - 9km NE of Aguanga, CA
1                  M 1.3 - 9km NE of Aguanga, CA
2                  M 3.4 - 8km NE of Aguanga, CA
3                  M 0.4 - 9km NE of Aguanga, CA
4                  M 2.2 - 10km NW of Avenal, CA
                          ...
9327        M 0.6 - 9km ENE of Mammoth Lakes, CA
9328                 M 1.0 - 3km W of Julian, CA
9329    M 2.4 - 35km NNE of Hatillo, Puerto Rico
9330               M 1.1 - 9km NE of Aguanga, CA
9331               M 0.7 - 9km NE of Aguanga, CA
Name: title, Length: 9332, dtype: object

We can use `loc` to select specific rows and columns without chaining. If we use row numbers with `loc`, they are now **inclusive** of the end index:

In [ ]:
# .loc[10:15, ['title', 'mag']] -> 10~15행(15 포함! 총 6행)의 title, mag 열
# 행은 범위로, 열은 리스트로. 이렇게 한 번에 행과 열을 고를 수 있음
df.loc[10:15, ['title', 'mag']]

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13
15       M 2.0 - 156km WNW of Haines Junction, Canada  2.00

#### Indexing with `iloc`
Exclusive of the endpoint just as Python slicing:

In [ ]:
# .iloc[행, 열] -> i = integer(정수). 이름이 아니라 '몇 번째'라는 위치 번호로 고르는 방식
# 10:15 -> 10번째부터 15 직전까지 = 10,11,12,13,14 (5행).
# [19, 8] -> 19번째 열(title), 8번째 열(mag). 열도 이름이 아니라 번호로
# 정리: loc = 이름으로 + 끝 포함 / iloc = 번호로 + 끝 미포함
df.iloc[10:15, [19, 8]]

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13

We can use slicing syntax with `iloc` for both rows and columns:

In [ ]:
# 행도 열도 번호 범위로. 10~14행, 6~9번째 열(gap, ids, mag, magType)
df.iloc[10:15, 6:10]

      gap             ids   mag magType
10   57.0    ,ci37389162,  0.50      ml
11  186.0  ,pr2018286010,  2.77      md
12   76.0    ,ci37389146,  0.50      ml
13  157.0    ,us1000hbti,  4.50      mb
14   71.0    ,nc73096921,  2.13      md

When using `loc`, we can slice on column names. This will be inclusive of the endpoint because you can't be expected to know what the next column name will be. As such, we have multiple ways to achieve the same end goal:

In [ ]:
# 위 iloc 결과와 loc로 같은 걸 골라보기
# loc[10:14, 'gap':'magType'] -> 10~14행(끝 포함), gap열부터 magType열까지(끝 포함)
# loc는 열 이름으로도 범위 지정 가능. .equals()로 비교하면 True
df.iloc[10:15, 6:10].equals(
    df.loc[10:14, 'gap':'magType']
)

True

### Looking up scalar values
We used `loc` and `iloc` to grab subsets of the dataframe. However, if we are just interested in the specific value at a given `[row, column]`, then we can use `iat` and `at`. We use `at` with labels:

In [ ]:
# .at[행이름, 열이름] -> 딱 한 칸의 값만 꺼낼 때. loc의 한 칸 전용 버전 (더 빠름)
# 10번 행의 mag 값 = 0.5
df.at[10, 'mag']

0.5

...and `iat` with integer indices:

In [ ]:
# .iat[행번호, 열번호] -> 위치 번호로 한 칸. iloc의 한 칸 전용 버전
# 10번째 행, 8번째 열 = mag = 0.5
df.iat[10, 8]

0.5

## Filtering
We can filter our dataframes using a **Boolean mask**, which can be made as follows:

In [ ]:
# df.mag > 2 -> 각 행마다 "규모가 2보다 큰가?" 를 True/False로 판단
# 결과는 9332개의 True/False가 든 시리즈. 이걸 Boolean mask(불리언 마스크)라고 함
# 마스크 = 가면. True인 행만 보이게 하고 False는 가리는 용도
df.mag > 2

0       False
1       False
2        True
3       False
4        True
        ...
9327    False
9328    False
9329     True
9330    False
9331    False
Name: mag, Length: 9332, dtype: bool

To use a mask for selection, we simply place it inside the brackets:

In [ ]:
# df[마스크] -> True인 행만 골라냄 = 필터링!
# 규모 7.0 이상인 지진만 -> 2개 나옴 (837번, 5263번)
# 이 패턴 df[df.열 조건]은 좀 중요한듯..
df[df.mag >= 7.0]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
837,green,4.1,1000haa3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.763,3.0,14.0,",us1000haa3,pt18283003,at00pgehsk,",7.0,mww,...,",us,pt,at,",reviewed,1539204500290,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",600.0,1539378744253,https://earthquake.usgs.gov/earthquakes/eventp...
5263,red,8.4,1000h3p4,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.589,18.0,27.0,",us1000h3p4,us1000h4p4,",7.5,mww,...,",us,us,",reviewed,1538128963480,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",480.0,1539123134531,https://earthquake.usgs.gov/earthquakes/eventp...

We can use masks with `loc`:

In [ ]:
# .loc[마스크, 열 리스트] -> 조건에 맞는 행 + 원하는 열만
# 규모 7.0 이상인 지진의 alert, mag, magType, title, tsunami, type 열만 보기
df.loc[
    df.mag >= 7.0,
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

Masks can be created using multiple criteria when combined with bitwise operators `&` for AND and `|` for OR. We must also surround each criterion with parentheses. We can't use `and`/`or` here because we need to evaluate row by row:

In [ ]:
# 조건 2개를 동시에: & 는 AND(그리고), | 는 OR(또는)
# (df.tsunami == 1) & (df.alert == 'red') -> 쓰나미 있고 AND 경보가 red인 행
# 주의 1: 각 조건은 반드시 괄호로 감싸야 함 (안 감싸면 에러)
# 주의 2: python_101에서 배운 and/or 를 쓰면 에러남! pandas에서 행마다 비교할 땐 &, | 를 써야 함
# -> 1개 (인도네시아 팔루 지진 7.5)
df.loc[
    (df.tsunami == 1) & (df.alert == 'red'),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

An example with an OR condition, which is less restrictive:

In [ ]:
# | (OR) -> 쓰나미가 있거나 OR 경보가 red인 행. 둘 중 하나만 맞아도 됨
# 조건이 느슨해지니까 결과가 훨씬 많아짐 (61개)
df.loc[
    (df.tsunami == 1) | (df.alert == 'red'),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
36,NaN,5.0,mww,"M 5.0 - 165km NNW of Flying Fish Cove, Christm...",1,earthquake
118,green,6.7,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
501,green,5.6,mww,"M 5.6 - 128km SE of Kimbe, Papua New Guinea",1,earthquake
799,green,6.5,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
816,green,6.2,mww,"M 6.2 - 94km SW of Kokopo, Papua New Guinea",1,earthquake
...,...,...,...,...,...,...
8561,NaN,5.4,mb,"M 5.4 - 228km S of Taron, Papua New Guinea",1,earthquake
8624,NaN,5.1,mb,"M 5.1 - 278km SE of Pondaguitan, Philippines",1,earthquake
9133,green,5.1,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake
9175,NaN,5.2,mb,"M 5.2 - 126km N of Dili, East Timor",1,earthquake
9304,NaN,5.1,mb,"M 5.1 - 34km NW of Finschhafen, Papua New Guinea",1,earthquake

Masks can be created from any criteria that results in a Boolean. For example, we can select all earthquakes with the string `Alaska` in the `place` column with a non-null value for the `alert` column. To get non-nulls, we can use the `isnull()` method with the bitwise negation operator (`~`) or the `notnull()` method:

In [ ]:
# df.place.str.contains('Alaska') -> place 열에 'Alaska'라는 글자가 들어있나? (python_101의 'h' in 'hello' 같은 거)
# df.alert.notnull() -> alert 열이 빈칸(NaN)이 아닌가? (isnull()의 반대. ~df.alert.isnull() 이라고 써도 같음)
# 두 조건 & -> 알래스카에서 났고 경보 값이 있는 지진
df.loc[
    (df.place.str.contains('Alaska')) & (df.alert.notnull()),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
1015,green,5.0,ml,"M 5.0 - 61km SSW of Chignik Lake, Alaska",1,earthquake
1273,green,4.0,ml,"M 4.0 - 71km SW of Kaktovik, Alaska",1,earthquake
1795,green,4.0,ml,"M 4.0 - 60km WNW of Valdez, Alaska",1,earthquake
2752,green,4.0,ml,"M 4.0 - 67km SSW of Kaktovik, Alaska",1,earthquake
3260,green,3.9,ml,"M 3.9 - 44km N of North Nenana, Alaska",0,earthquake
4101,green,4.2,ml,"M 4.2 - 131km NNW of Arctic Village, Alaska",0,earthquake
6897,green,3.8,ml,"M 3.8 - 80km SSW of Kaktovik, Alaska",0,earthquake
8524,green,3.8,ml,"M 3.8 - 69km SSW of Kaktovik, Alaska",0,earthquake
9133,green,5.1,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake

We can even use regular expressions here:

In [ ]:
# r'CA$|California$' -> 정규표현식(regex). 문자열 패턴을 찾는 특수 문법
#   $ = 문자열의 끝, | = 또는 → "CA로 끝나거나 California로 끝나는"
#   r'' 는 raw string. 정규표현식 쓸 때 앞에 r 붙이면 특수문자가 그대로 전달됨
# & (df.mag > 3.8) -> 그리고 규모 3.8 초과
# -> 캘리포니아에서 난 3.8 넘는 지진 2개
df.loc[
    (df.place.str.contains(r'CA$|California$')) & (df.mag > 3.8),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
1465,green,3.83,mw,"M 3.8 - 109km WNW of Trinidad, CA",0,earthquake
2414,green,3.83,mw,"M 3.8 - 5km SW of Tres Pinos, CA",1,earthquake

We can use the `between()` method to turn 2 individual checks (is less than or equal to some maximum value and is greater than or equal to some minimum value) into a single one. Note this is inclusive of the endpoint by default:

In [ ]:
# .between(6.5, 7.5) -> 6.5 이상 7.5 이하인가? (양 끝 포함)
# (df.mag >= 6.5) & (df.mag <= 7.5) 를 한 번에 쓴 거임
df.loc[
    df.mag.between(6.5, 7.5),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
118,green,6.7,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
799,green,6.5,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
4363,green,6.7,mww,"M 6.7 - 263km NNE of Ndoi Island, Fiji",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

We can use the `isin()` method to check for membership in a list of values:

In [ ]:
# .isin(['mw', 'mwb']) -> 값이 이 리스트 안에 있나? mw 또는 mwb인 행
# (df.magType == 'mw') | (df.magType == 'mwb') 를 한 번에. 후보가 많을 때 편함
df.loc[
    df.magType.isin(['mw', 'mwb']),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
995,NaN,3.35,mw,"M 3.4 - 9km WNW of Cobb, CA",0,earthquake
1465,green,3.83,mw,"M 3.8 - 109km WNW of Trinidad, CA",0,earthquake
2414,green,3.83,mw,"M 3.8 - 5km SW of Tres Pinos, CA",1,earthquake
4988,green,4.41,mw,"M 4.4 - 1km SE of Delta, B.C., MX",1,earthquake
6307,green,5.80,mwb,"M 5.8 - 297km NNE of Ndoi Island, Fiji",0,earthquake
8257,green,5.70,mwb,"M 5.7 - 175km SSE of Lambasa, Fiji",0,earthquake

We can grab the index of the minimum and maximum values of a given column and use those to select the entire row where they occur:

In [ ]:
# .idxmin() -> 최솟값이 있는 행의 인덱스(이름표) / .idxmax() -> 최댓값이 있는 행의 인덱스
# idx = index. 값 자체가 아니라 '어느 행에 있나'를 알려줌
# -> 규모가 가장 작은 지진은 2409번 행, 가장 큰 지진은 5263번 행
[df.mag.idxmin(), df.mag.idxmax()]

[2409, 5263]

In [ ]:
# 위에서 찾은 인덱스 2개를 .loc에 리스트로 넣어서 그 행들만 꺼냄
# 규모 -1.26 (제일 작음) 과 7.5 (제일 큼)
df.loc[
    [df.mag.idxmin(), df.mag.idxmax()],
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
2409,NaN,-1.26,ml,"M -1.3 - 41km ENE of Adak, Alaska",0,earthquake
5263,red,7.50,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

Note that there is a `filter()` method, but it doesn't filter the data in the same sense as we discussed in this section. Here are a few things you can do with this method.

- grab columns of a dataframe by passing a list to `items`:

In [ ]:
# .filter() -> 이름은 filter지만 '조건으로 행 거르기'가 아니라 '열/행 이름으로 고르기' 기능임. 헷갈리기 쉬움!
# items=['mag', 'magType'] -> 이 이름의 열들만. df[['mag', 'magType']]와 같음
df.filter(items=['mag', 'magType']).head()

    mag magType
0  1.35      ml
1  1.29      ml
2  3.42      ml
3  0.44      ml
4  2.16      md

- grab all the columns that contain a string with the `like` parameter:

In [ ]:
# like='mag' -> 열 이름에 'mag'가 들어간 것 전부 -> mag, magType
df.filter(like='mag').head()

    mag magType
0  1.35      ml
1  1.29      ml
2  3.42      ml
3  0.44      ml
4  2.16      md

- use regular expressions; here, we select any columns that start with `t`:

In [ ]:
# regex=r'^t' -> 정규표현식. ^ = 시작 -> 't'로 시작하는 열 이름 전부 (time, title, tsunami, type, types, tz)
df.filter(regex=r'^t').head()

,time,title,tsunami,type,types,tz
0,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0
1,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0
2,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0
3,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0
4,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0

- use `filter()` along the rows, by passing in `axis=0`. Here, we will use the `place` column as the index (we will cover `set_index()` in chapter 3):

In [ ]:
# 여러 명령어를 점(.)으로 이어 붙인 체이닝. 왼쪽부터 순서대로 읽으면 됨
# 1) df.set_index('place') → place 열을 인덱스(행 이름표)로 바꿈 (3장에서 자세히)
# 2) .filter(like='Japan', axis=0) → axis=0 은 '행 방향'. 행 이름(=place)에 'Japan'이 들어간 행만
# 3) .filter(items=['mag', 'magType', 'title']) → 그 중 이 열들만
# 4) .head() → 위 5개만
df.set_index('place').filter(like='Japan', axis=0).filter(items=['mag', 'magType', 'title']).head()

                             mag magType                                title
place
160km NNW of Nago, Japan     4.6      mb     M 4.6 - 160km NNW of Nago, Japan
7km ESE of Asahi, Japan      5.2     mww      M 5.2 - 7km ESE of Asahi, Japan
14km E of Tomakomai, Japan   4.5     mwr   M 4.5 - 14km E of Tomakomai, Japan
139km WSW of Naze, Japan     4.7      mb     M 4.7 - 139km WSW of Naze, Japan
53km ESE of Kamaishi, Japan  4.6      mb  M 4.6 - 53km ESE of Kamaishi, Japan

This also works on `Series` objects and will run on the index:

In [ ]:
# 시리즈에도 filter 가능. 시리즈는 열이 하나니까 인덱스 기준으로 걸러짐
# place를 인덱스로 → title 열만 꺼내서(시리즈) → 인덱스에 Japan 들어간 것만
df.set_index('place').title.filter(like='Japan').head()

place
160km NNW of Nago, Japan          M 4.6 - 160km NNW of Nago, Japan
7km ESE of Asahi, Japan            M 5.2 - 7km ESE of Asahi, Japan
14km E of Tomakomai, Japan      M 4.5 - 14km E of Tomakomai, Japan
139km WSW of Naze, Japan          M 4.7 - 139km WSW of Naze, Japan
53km ESE of Kamaishi, Japan    M 4.6 - 53km ESE of Kamaishi, Japan
Name: title, dtype: object

<hr>
<div>
    <a href="./4-inspecting_dataframes.ipynb">
        <button style="float: left;">&#8592; Previous Notebook</button>
    </a>
    <a href="./6-adding_and_removing_data.ipynb">
        <button style="float: right;">Next Notebook &#8594;</button>
    </a>
</div>
<br>
<hr>